name: domain
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  bloc: ^8.1.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  lints: ^2.1.0
  test: ^1.24.0
